;/*******************************
; * Site: Project Euler
; * Link: http://projecteuler.net/problems
; * Problem:
; * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
; * 
; *     22=4, 23=8, 24=16, 25=32
; *     32=9, 33=27, 34=81, 35=243
; *     42=16, 43=64, 44=256, 45=1024
; *     52=25, 53=125, 54=625, 55=3125
; * 
; * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
; * 
; * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
; * 
; * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
; * 
; * Solution by: David
; * Answer: 9183
; *
; * Comment :
; *******************************/

(defun pow (n p)
  "Returns n^p"
  (cond ((zerop p)
	 1)
	((= 2 p)
	 (* n n))
	((zerop (mod p 2))
	 (pow (pow n (/ p 2)) 2))
	(t
	 (* n (pow n (1- p))))))

(defun list-pow (a bi bf)
  "Returns the list (a^bf ... a^bi)"
  (if (> bi bf)
      ()
      (cons (pow a bf) (list-pow a bi (1- bf)))))

(list-pow 3 2 5)

(defun list-double-pow (ai af bi bf)
  "Returns the list"
  (if (> ai af)
      ()
      (append (list-pow af bi bf) (list-double-pow ai (1- af) bi bf))))

(time (length (remove-duplicates (list-double-pow 2 100 2 100))))
;->9183
